version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ops/api.dockerfile
    env_file:
      - ./ops/.env.prod
    ports:
      - "4000:4000"
    extra_hosts:
      - "host.docker.internal:127.0.0.1"
    command: node server/api.js
  spider:
    build:
      context: .
      dockerfile: ops/spider.dockerfile
    extra_hosts:
      - "host.docker.internal:127.0.0.1"
    ports:
      - "4010:4010"
    network_mode: "host"
    env_file:
      - ./ops/.env.prod
    command: node server/spider.js
