version: '3'
services:

  balancer:
    image: nginx:1.24-alpine-slim
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ops/nginx:/etc/nginx:ro
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html
    command: nginx

  api:
    build:
      context: .
      dockerfile: ops/api.dockerfile
    env_file:
      - ./ops/.env.prod
    network_mode: "host"
    command: node server/api.js

  spider:
    build:
      context: .
      dockerfile: ops/spider.dockerfile
    network_mode: "host"
    env_file:
      - ./ops/.env.prod
    command: node server/spider.js
