version: '3'
services:

  balancer:
    image: nginx:1.24-alpine-slim
    network_mode: "host"
    volumes:
      - ./ops/nginx:/etc/nginx:ro
      - /var/www/html:/var/www/html:ro
      - ./ops/certs:/var/www/certbot:ro
      - ./ops/certs:/etc/letsencrypt:ro

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./ops/certs:/var/www/certbot:rw
      - ./ops/certs:/etc/letsencrypt:rw
    depends_on:
      - balancer
    command: >-
      certonly --reinstall --webroot --webroot-path=/var/www/certbot
      --email shu@immux.com --agree-tos --no-eff-email
      -d aimm.dev -d *.aimm.dev

  api:
    build:
      context: .
      dockerfile: ops/api.dockerfile
    env_file:
      - ./ops/.env.prod
    network_mode: "host"
    command: node server/api.js

  spider:
    build:
      context: .
      dockerfile: ops/spider.dockerfile
    network_mode: "host"
    env_file:
      - ./ops/.env.prod
    command: node server/spider.js
