version: '3'
services:

  web:
    build:
      context: .
      dockerfile: ops/web.dockerfile
    env_file:
      - ./ops/.env.prod
    network_mode: "host"
    command: node node_modules/.bin/http-server build/web --port 3000

  api:
    build:
      context: .
      dockerfile: ops/api.dockerfile
    env_file:
      - ./ops/.env.prod
    network_mode: "host"
    command: node server/api.js

  spider:
    build:
      context: .
      dockerfile: ops/spider.dockerfile
    network_mode: "host"
    env_file:
      - ./ops/.env.prod
    command: node server/spider.js
