version: '3'
services:

  balancer:
    image: nginx:1.24-alpine-slim
    network_mode: "host"
    volumes:
      - ./ops/nginx:/etc/nginx:ro
      - /var/www/html:/var/www/html:ro
      - ./ops/certs:/etc/letsencrypt:ro

  api:
    build:
      context: .
      dockerfile: ops/api.dockerfile
    env_file:
      - ./ops/.env.prod
    network_mode: "host"
    command: node server/api.js

  spider:
    build:
      context: .
      dockerfile: ops/spider.dockerfile
    network_mode: "host"
    env_file:
      - ./ops/.env.prod
    command: node server/spider.js
